### ISSUE TITLE
'expl' should normally be 'PRON' but it is 'AUX'

### ISSUE THREAD

**Issue by bulbulistan** [UniversalDependencies/UD_Maltese-MUDT#2]
This affects cleft sentences of the "It is him who... / It was in December that ... / It is sad that ..." type. In Maltese, the expletive pronoun used here is 3SGM or 3SGF (UPOS PRON, XPOS PRON_PERS), but only in the present. For the past and the future, the appropriate forms of the verb "kien" are used (UPOS AUX, XPOS KIEN) and since Maltese is one of those languages that encode subjects morphologically on the verb, no pronoun is used, Thus the error. 
What would be the solution here? The only one I can think of it using something like "cop:expl". Is there any other option?

**Comment by jnivre** [comment]
I am not sure I completely understand the construction, but if it is a case of pro-drop then there is no expletive pronoun at all. (UD never annotates the morphological person inflection on the verb as a pronoun. This falls under the principle "do not annotate things that don't exist in a language just because it exists in other languages".

**Comment by bulbulistan** [comment]
To give an example:
Present - "Hi ċara li ..." = "She clear that ..." = "It is clear that..."
Past - "Kienet ċar li ..." = "be.PAST.3SGF clear that ..." = "It was clear that ..."
Future - "Tkun ċara  li ..." = IMPF.3SGF.be clear that ..." = "It will be clear that ..."

And yes, there is no expletive pronoun in the past, the question is, what is "kien"? It takes the same slot as the expletive pronoun and this alternation of  personal pronoun and "kien" is the same as the one for copular clauses; on the other hand, these types of clauses are different from copular clauses in a number of aspects. Does "cop:expl" seem like a good general solution?

**Comment by jnivre** [comment]
First of all, these look like extraposed subject clauses rather than clefts to me, but the most natural analysis would seem to annotate "Hi" as "expl" in the first clause and "Kienet" and "Tkun" as "cop" in the latter too. Alternatively, you can treat "Hi" as a nonverbal copula if that makes sense (which would increase the parallelism). For comparison, in the corresponding English sentences "it is clear that", "it" is "expl" and "is" is "cop".
